from enum import Enum

# NBA_TEAMS list as an Enum
class TeamEnum(str, Enum):
    Atlanta_Hawks = "Atlanta Hawks"
    Boston_Celtics = "Boston Celtics"
    Brooklyn_Nets = "Brooklyn Nets"
    Charlotte_Hornets = "Charlotte Hornets"
    Chicago_Bulls = "Chicago Bulls"
    Cleveland_Cavaliers = "Cleveland Cavaliers"
    Dallas_Mavericks = "Dallas Mavericks"
    Denver_Nuggets = "Denver Nuggets"
    Detroit_Pistons = "Detroit Pistons"
    Golden_State_Warriors = "Golden State Warriors"
    Houston_Rockets = "Houston Rockets"
    Indiana_Pacers = "Indiana Pacers"
    Los_Angeles_Clippers = "Los Angeles Clippers"
    Los_Angeles_Lakers = "Los Angeles Lakers"
    Memphis_Grizzlies = "Memphis Grizzlies"
    Miami_Heat = "Miami Heat"
    Milwaukee_Bucks = "Milwaukee Bucks"
    Minnesota_Timberwolves = "Minnesota Timberwolves"
    New_Orleans_Pelicans = "New Orleans Pelicans"
    New_York_Knicks = "New York Knicks"
    Oklahoma_City_Thunder = "Oklahoma City Thunder"
    Orlando_Magic = "Orlando Magic"
    Philadelphia_76ers = "Philadelphia 76ers"
    Phoenix_Suns = "Phoenix Suns"
    Portland_Trail_Blazers = "Portland Trail Blazers"
    Sacramento_Kings = "Sacramento Kings"
    San_Antonio_Spurs = "San Antonio Spurs"
    Toronto_Raptors = "Toronto Raptors"
    Utah_Jazz = "Utah Jazz"
    Washington_Wizards = "Washington Wizards"